"""added test_files

Revision ID: 923b6d257c8f
Revises: 0a6d01e62ad2
Create Date: 2021-09-27 18:56:30.197467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "923b6d257c8f"
down_revision = "0a6d01e62ad2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cloud",
        sa.Column(
            "machine_type",
            sa.String(length=64),
            nullable=False,
            server_default="n2-standard-2",
        ),
    )
    op.add_column(
        "test",
        sa.Column(
            "machine_type",
            sa.String(length=64),
            nullable=False,
            server_default="n2-standard-2",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test", "machine_type")
    op.drop_column("cloud", "machine_type")
    # ### end Alembic commands ###
