"""added test parameters

Revision ID: bc9fc9178a89
Revises: fe761c3b3c6f
Create Date: 2021-10-14 16:31:21.780952

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = "bc9fc9178a89"
down_revision = "fe761c3b3c6f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test",
        sa.Column(
            "finish_date",
            sa.DateTime(),
            nullable=True,
            # server_default=func.now(),
        ),
    )
    op.add_column(
        "test",
        sa.Column(
            "start_date",
            sa.DateTime(),
            # nullable=False,
            # server_default=func.now(),
        ),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("start_date")
    op.drop_column("finish_date")

    # ### end Alembic commands ###
