"""added endpoint 'is_service'

Revision ID: 20ecbfdde016
Revises: acf6d1eb84a1
Create Date: 2021-11-24 12:26:43.290393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ecbfdde016'
down_revision = 'acf6d1eb84a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint', sa.Column('is_service', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoint', 'is_service')
    # ### end Alembic commands ###
