"""added test region

Revision ID: acf6d1eb84a1
Revises: d77279c62804
Create Date: 2021-11-03 15:51:24.045848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "acf6d1eb84a1"
down_revision = "d77279c62804"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test",
        sa.Column(
            "region",
            sa.String(length=64),
            nullable=False,
            server_default="europe-west4-a",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test", "region")
    # ### end Alembic commands ###
