"""added name to test

Revision ID: d77279c62804
Revises: bc9fc9178a89
Create Date: 2021-10-14 17:44:11.051312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77279c62804'
down_revision = 'bc9fc9178a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'name')
    # ### end Alembic commands ###
